# Generated by Django 4.1.6 on 2023-02-13 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_block_document_delete_post_block_block_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='block_order',
            field=models.IntegerField(default=0),
        ),
    ]
