# Generated by Django 4.1.7 on 2023-03-09 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_block_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'ordering': ['block_order']},
        ),
    ]
