services:
  database:
    image: postgres:14.5
    volumes:
      - sweng-db:/var/lib/postgresql/data
    environment: &env
      POSTGRES_HOST: ${POSTGRES_HOST:-database}
      POSTGRES_USER: ${POSTGRES_USER:-dev}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dev}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_DB:-database}
  webserver:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment: *env
    links:
        - database:database
volumes:
  sweng-db:
