services:
  database:
    image: postgres:14.5
    volumes:
      - sweng-db:/var/lib/postgresql/data
    environment: &environment
      POSTGRES_HOST: database
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_PORT: 5432
      POSTGRES_DB: database
    ports:
      - 8081:5432
  webserver: &webserver
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        BUNDLE: local
    environment: *environment
    ports:
      - 8080:80
    links:
        - database:database
  webserver-local:
    <<: *webserver
    volumes:
      - ../client:/var/www/apache/client:ro
      - ../server:/var/www/apache/server:ro
      - ../api:/var/www/apache/api:ro
      - ../scripts:/var/www/apache/scripts:ro
    entrypoint: [ "bash", "scripts/run-local.bash" ]
volumes:
  sweng-db:
