name: CD to Docker Hub

on:
  create:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set BING token
        env:
          BING_API_KEY: "${{ secrets.AZURE_TOKEN }}"
          
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Set env
        id: env_task 
        run: |
          echo "tag=$(git describe --tags)" >> $GITHUB_OUTPUT
# steps.env_task.outputs.tag
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/legal_spellcheck:${{ steps.env_task.outputs.tag }}
          build-args: BUNDLE=production
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
